language: ruby
bundler_args: --without local_development
script: bundle exec rake
# gemfile:
#   - gemfiles/Gemfile.ci
# before_install: some_command
# env:
#   - "rack=1.3.4"
before_install:
  - gem install bundler
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
